object_detection_node:
  ros__parameters:
    model: "yolov8n.pt"         # yolov8n / yolov8s / yolov8m
    confidence: 0.10       # 0.0 - 1.0
    camera_topic: "/camera/image_raw"
    show_window: true
